### ISSUE TITLE
Integrate allodb and bmss

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/fgeo.biomass#1]
@gonzalezeb, 

Where in the table should the code look for the parameters in the column `equation`?

It is clear that `DBH` is a measurement that the user must provide for each stem. But is it not clear where the other parameters come from. Should we give them in the `equations` table? Should the user get them from somewhere else and feed them into our code?

For example, where should the code get `a` from? Or `b`, or `d`? Also, is there a lookup table to know what each of those parameters mean?

```R
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(allodb)

head(equations$equation)
#> [1] "a*(DBH^2)^b"       "a*(DBH^2)^b"       "a+b*DBH+c*(DBH^d)"
#> [4] "a+b*DBH+c*(DBH^d)" "a+b*DBH+c*(DBH^d)" "a+b*DBH+c*(DBH^d)"
glimpse(equations)
#> Observations: 421
#> Variables: 23
#> $ equation_id                  <chr> NA, NA, NA, NA, NA, NA, NA, NA, N...
#> $ biomass_component            <chr> "Stem and branches (live)", "Stem...
#> $ equation                     <chr> "a*(DBH^2)^b", "a*(DBH^2)^b", "a+...
#> $ allometry_specificity        <chr> "Species", "Species", "Species", ...
#> $ development_species          <chr> NA, NA, NA, "Ulmus americana", NA...
#> $ geographic_area              <chr> "North Carolina, Georgia", "North...
#> $ dbh_min_cm                   <chr> "14.22", "29.46", "2.5", "2.5", "...
#> $ dbh_max_cm                   <chr> "25.91", "41.66", "40", "40", "55...
#> $ n_trees                      <int> 9, 9, NA, NA, NA, NA, NA, NA, NA,...
#> $ dbh_units_original           <chr> "in", "in", "cm", "cm", "mm", "mm...
#> $ biomass_units_original       <chr> "lb", "lb", "kg", "kg", "kg", "kg...
#> $ allometry_development_method <chr> "harvest", "harvest", "harvest", ...
#> $ model_parameters             <chr> "DBH", "DBH", "DBH", "DBH", "DBH"...
#> $ regression_model             <chr> "linear_multiple", "linear_multip...
#> $ other_equations_tested       <chr> "yes", "yes", NA, NA, NA, NA, NA,...
#> $ log_biomass                  <chr> "10", "10", NA, NA, NA, NA, NA, N...
#> $ bias_corrected               <chr> "yes", "yes", "no", "no", "no", "...
#> $ bias_correction_factor       <chr> "included in model", "included in...
#> $ notes_fitting_model          <chr> "Regression equations were develo...
#> $ original_data_availability   <chr> "1", "1", NA, NA, NA, NA, NA, NA,...
#> $ notes_to_consider            <chr> NA, NA, NA, NA, NA, NA, "DBA = ba...
#> $ warning                      <chr> NA, NA, NA, NA, NA, NA, NA, NA, N...
#> $ ref_id                       <chr> NA, NA, NA, NA, NA, NA, NA, NA, N...
```

**Comment by maurolepore** [comment]
@gonzalezeb,

[This post](https://bookdown.org/fgeocomm/36_integrate/) brakes down the process of calculating biomass from a table of allometric equations (that we provide) and a table with dbh measurements (that the user provides). This is to more clearly show what I think it is missing from our table of equations.

**Comment by gonzalezeb** [comment]
The parameters a, b, d, or d are in our master table. These are the coefficients used for the regression equations compiled from the original publications. 

We originally though that we could replace these parameters in the actual equation, i.e, instead of having a*DBH^b on the equation column we will have 4.13741*DBH*1.08876. 

If you thinks is best, I will modify the data.Rmd so those columns will be included on the equation table.

**Comment by maurolepore** [comment]
Great! Yes, I agree that ` 4.13741DBH*1.08876` is better than `aDBH^b`.

So we still need to do the conversion, right? I'll have a look to see how big is the challenge to do this in R. 

Do you have any other suggestion? I recently learned about [OpenRefine](http://openrefine.org/) -- which might be good to keep in mind.

**Comment by gonzalezeb** [comment]
Yes, we still need to the conversion. Maybe by ‘concatenating’ the needed columns using paste? I will give it a try.

**Comment by maurolepore** [comment]
Good news, a quick try shows that we can replace the parameters a-d. This relies on matching strings so we have to be careful to avoid mismatches. For example, if we replace a by A from apple we get Apple. But if we replace a by A in america we get AmericA .

But I still wonder where to get some other parameters. 

All of this is in section 2 of [this document](https://bookdown.org/fgeocomm/36_integrate/)

**Comment by gonzalezeb** [comment]
I fixed the "other parameters" which were actually part of the original equations. I rewrote equations that needed to take a more general form (ie, ln(BST)=a+b*ln(DBH) changed to exp(a+b*ln(DBH)..

**Comment by maurolepore** [comment]
Great! OK, then I'll soon rerun the replacement -- which should result in equations that are only a function of `DBH`. I'll be in touch in a day or so.

**Comment by gonzalezeb** [comment]
There are now 16 unique equations but notice that 11 and 12 have 2 extra variables (WD and Bk) that are embedded within the formula. 

> distinct(master, equation)
                                     equation
1                                 a*(DBH^2)^b
2                                   a*(DBH^b)
3                           a+b*DBH+c*(DBH^d)
4                                   a*(DBA^b)
5                            exp(a+b*ln(DBH))
6                  exp(a+b*DBH+c*(ln(DBH^d)))
7                       10^a+b*(log10(DBH^c))
8                                     a+b*DBH
9                                      a+b*BA
10                           exp(a+b*ln(DBA))
11 exp(a+b×ln(DBH))*WD*Bk(WD=419.814,Bk=1.22)
12 exp(a+b×ln(DBH))*WD*Bk(WD=645.704,Bk=1.05)
13                                 10^a*DBH^b
14              a+(b*DBH)+c*(DBH^2)+d*(DBH^3)
15                   NA                        
16                    exp(a+(b*(ln(pi*DBH))))
17                       exp(a+b*(DBH/DBH+c))

**Comment by gonzalezeb** [comment]
Now, also notice that some equations are a function of DBA (diameter at base) or BA (basal area). Calculating BA is a step that needs to happen before the actual biomass calculation. Valentine, already wrote a code to:

* Calculate basal area contribution of each stem within a tree.
* Redistribute the biomass of main stem to other stem, using the basal contribution For an idea you see it [here](https://github.com/EcoClimLab/ForestGEO_global_tree-size/blob/master/allometries/ucsc_Allometries.R).

**Comment by maurolepore** [comment]
Mmm this brings too many questions. There are tiny details that can easily lead to confusion and result in a completely wrong result. __I think we should meet one day and work on this together -- with excel, R or whatever -- until we clean all equations__. Then you can continue to collect new equations and format them consistently with what we achieve in our meeting. What do you think? If OK, when would it work for you?

For our records, here I list que questions that come to my mind right away.

* (a) How should equations 11 and 12 be replaced? Can you replace them here manually to see if I can express that in code?

* (b) Are `BA` and `DBA` the exact same thing? If so, we need to pick one and drop the other one --
 I suggest keep `BA` and drop `DBA` because `DBA` confuses with `DBH`. `DBA` leaves the reader thinking, Did you really mean `DBH` or did you type an `H` instead of an `A`, just by mistake?

* (c) Are the precedence rules correctly expressed within each equation? For example equation 5:

```R
# literal copy paste
exp(a+bln(DBH))

# I think that by `bln` you mean `b * ln(...). 
# Here I use parenthesis to explicitely show precedence rules:
exp(   a +  ( b * ln(DBH) )    )

# Is this the same?
ln_dbh <- ln(DBH)
b_times_ln_dbh <- b * ln_dbh
exp(a + b_times_ln_dbh)
```

* (d) In equations 11 and 12, is `b × ln(` the same as` b * ln(` ?

**Comment by gonzalezeb** [comment]
I run distinct(master, equation) again and got the correct equations:

```R
1                      a*(DBH^2)^b
2                        a*(DBH^b)
3                a+b*DBH+c*(DBH^d)
4                        a*(DBA^b)
5                 exp(a+b*ln(DBH))
6       exp(a+b*DBH+c*(ln(DBH^d)))
7            10^a+b*(log10(DBH^c))
8                          a+b*DBH
9                           a+b*BA
10                exp(a+b*ln(DBA))
11 exp(a+(b*ln(DBH)))*419.814*1.22
12 exp(a+(b*ln(DBH)))*645.704*1.05
13                      10^a*DBH^b
14   a+(b*DBH)+c*(DBH^2)+d*(DBH^3)
15                          NA     
16         exp(a+(b*(ln(pi*DBH))))
17            exp(a+b*(DBH/DBH+c))
```

But I will have to check on the precedent rules....

**Comment by gonzalezeb** [comment]
BA and DBA are not the same, we will need to reconsider strategies.

**Comment by maurolepore** [comment]
Great! This addresses almost all my concerns. Here are the few things that I still need to ask you or think about:

* DBA and BA: Now I see: One is _diameter_ and the other is _area_ -- sorry for not reading this carefully enough. I wonder if one can be expressed as a funcition of the other with Valentine's code -- the link to her work didn't work for me. Is it in a public repo? ([here](https://github.com/EcoClimLab/ForestGEO_global_tree-size/blob/master/allometries/ucsc_Allometries.R)).

* What should we do when the value of `equation` is `NA`?

* Review `equation` 17: `exp(a+b*(DBH/DBH+c))`.

```R
DBH <- 2
c <- 1

# Notice how parentheses produce different results
DBH / DBH + c
#> [1] 2
DBH / (DBH + c)
#> [1] 0.6666667
```

My updates notes are in section 2 [here](https://bookdown.org/fgeocomm/36_integrate/).

**Comment by maurolepore** [comment]
Function to calculate basal area:

https://forestgeo.github.io/fgeo.abundance/reference/basal_area.html

**Comment by maurolepore** [comment]
Today I wrote some funcitons to compute biomass with data from SCBI and site-level equations from __allodb__. For an example see [README](https://github.com/forestgeo/allodb/blob/58data/README.md#example).

At least for now, the code lives in __allodb__ instead of __bmss__ because it mostly restructures and combines data from __allodb__. The logic that __bmss__ has is not yet available. Instead, the code follows a simple path to computing biomass. 

Tomorrow I'll revisit this code with a fresh brain, and will test it more. Then I'll think what's next.

**Comment by maurolepore** [comment]
@gonzalezeb and @teixeirak,

Today I pre-released [__fgeo.biomass__ 0.0.0.9000](https://github.com/forestgeo/fgeo.biomass/releases/tag/0.0.0.9000). 

* [Overview](https://forestgeo.github.io/fgeo.biomass/index.html#overview).
* [Reference](https://forestgeo.github.io/fgeo.biomass/reference/index.html).

With this I finish this iteration of the integration between __allodb__ and __fgeo.biomass__. There is still a lot to do and I already plan [some improvements](https://forestgeo.github.io/fgeo.biomass/index.html#possible-improvements). But before I continue it would be great to get feedback from you and whoever you want to share this work with.

**Comment by maurolepore** [comment]
Closing because this issue is unfocused. We may later extract the bits we need and follow up.
